WIP patch to demonstrate problem
Apply and run 'make check' to see the problem.  I've created an
empty expected output file, just to keep the regression test
infrastructure happy.

The problem manifests as:

ERROR:  could not determine which collation to use for string hashing