Remove unused global variable [pg_dump]
src/bin/pg_dump/pg_dump_sort.c:160:15: error: variable 'preDataBoundId' set but not used [-Werror,-Wunused-but-set-global]

This was apparently never used (initial commit a1ef01fe163).