Make ON CONFLICT DO NOTHING and ON CONFLICT DO UPDATE consistent
Prior to this commit we allowed self-conflicting inserts for DO NOTHING:

  CREATE TABLE t (a INT UNIQUE, b INT);
  INSERT INTO t VALUES (1,1), (1,2) ON CONFLICT DO NOTHING;
  -- succeeds, inserting the first row and ignoring the second

... but not for DO UPDATE:

  INSERT INTO t VALUES (1,1), (1,2) ON CONFLICT (a) DO UPDATE SET b = 0;
  ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time

Now DO UPDATE is handled similarly to DO NOTHING.

Author: Aleksander Alekseev
Reviewed-by: Andres Freund, TODO FIXME
Discussion: https://postgr.es/m/CAJ7c6TPQJNFETz9H_qPpA3x7ybz2D1QMDtBku_iK33gT3UR34Q%40mail.gmail.com