Remove unused global variable [postmaster]
src/backend/postmaster/postmaster.c:372:13: error: variable 'ReachedNormalRunning' set but not used [-Werror,-Wunused-but-set-global]

The last use was removed in commit 39969e2a1e4.