Fix race with LLVM compilation and bison code generation.
In case when source file is compiled with LLVM and include header file
that should be generated by bison, compile error can occur, example:

cubescan.c:9:10: fatal error: 'cubeparse.h' file not found
    9 | #include "cubeparse.h"

The reason is race, that exist between LLVM compilation and bison code
generation and compilation can occur first. Ideally LLVM compilation
target should depend on .o files targets.