Remove unused global variable [xlog.c]
src/backend/access/transam/xlog.c:675:19: error: variable 'LocalMinRecoveryPointTLI' set but not used [-Werror,-Wunused-but-set-global]

This was apparently never used (initial commit 70e81861fad).

Discussion: https://www.postgresql.org/message-id/flat/eb013f9d-2247-444e-8815-9d17b4ce78e7%40eisentraut.org