ALTER TABLE command to change policy
This change prevents ALTER TABLE … ALTER COLUMN SET DATA TYPE from failing when
the column has dependent policy objects, whereas previously it would raise an
error.

The approach closely mirrors how statistics are rebuilt: identify all policy
objects that need to be rebuilt, construct their CREATE definitions, and then
recreate those objects.

However, we must fail when the qual or WITH CHECK clause contains a subquery.
Otherwise, we would need to acquire AccessExclusiveLock on the referenced tables
too, which seems not good, for example, changing dtaa type in table t would also
lock table t1 in AccessExclusiveLock

CREATE TABLE t(a int);
CREATE TABLE t1(a int);
CREATE POLICY p2 ON t1 AS PERMISSIVE USING ((SELECT t.a IS NOT NULL FROM t));
ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT8;
ERROR:  cannot alter type of a column used by a policy definition when the policy contains subquery
DETAIL:  policy p2 on table t depends on column "a"

Another reason to disallow subqueries in qual or WITH CHECK clauses is that,
internally, we reconstruct policy definitions. Recreating such policies can
trigger repeated RangeVar name lookups, leading to correctness and robustness
issues.

discussion: https://postgr.es/m/CACJufxE42vysVEDEmaoBGmGYLZTCgUAwh_h-c9dcSLDtD5jE3g@mail.gmail.com